version: "3"
services:
  app:
    image: dirkzzz/badminton-go
    container_name: badminton-go
    restart: always
    ports:
      - "8080:3050"
    depends_on:
      - 'mongo'
  mongo:
    image: mongo
    container_name: mongo