version: "3"
services:
  app:
    container_name: badminton-go
    restart: always
    build: ./
    ports:
      - "8080:3050"
    volumes:
      - .:/app
    depends_on:
      - 'mongo'
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"